# Generated by Django 5.2.17 on 2026-09-30 16:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('country_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stage', models.CharField(choices=[('LOAN_DOCUMENTS', 'Loan Work / Documents'), ('FEASIBILITY', 'Feasibility'), ('STRUCTURE', 'Structure Work'), ('ELECTRICAL', 'Electrical Work'), ('KSEB_DOCUMENTATION', 'KSEB Documentation'), ('SUBSIDY_DOCUMENTATION', 'Subsidy Documentation'), ('COMPLETED', 'Completed')], default='LOAN_DOCUMENTS', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_works', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_works', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='leads.lead')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='leads.solarplan')),
            ],
            options={
                'indexes': [models.Index(fields=['stage'], name='works_work_stage_idx'), models.Index(fields=['due_date'], name='works_work_due_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stage__in', ['LOAN_DOCUMENTS', 'FEASIBILITY', 'STRUCTURE', 'ELECTRICAL', 'KSEB_DOCUMENTATION', 'SUBSIDY_DOCUMENTATION', 'COMPLETED'])), name='works_work_stage_valid'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='works_work_amount_non_negative')],
            },
        ),
    ]
