# Generated by Django 5.2.17 on 2026-10-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
