# Generated by Django 5.2.17 on 2026-10-07 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(choices=[('bank_passbook', 'Bank passbook'), ('aadhar_card', 'Aadhaar card'), ('pan_card', 'PAN card'), ('electricity_bill', 'Electricity bill'), ('site_photo', 'Site photo'), ('land_tax_paper', 'Land tax paper'), ('name_signature', 'Name & signature (white paper)'), ('dcr', 'DCR'), ('gps_photo', 'GPS photo'), ('inverter_serial_number', 'Inverter serial number')], max_length=40)),
                ('cloudinary_public_id', models.CharField(max_length=255, unique=True)),
                ('cloudinary_resource_type', models.CharField(max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='works.work')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('work', 'document_key'), name='works_document_one_per_key'), models.CheckConstraint(condition=models.Q(('document_key__in', ['bank_passbook', 'aadhar_card', 'pan_card', 'electricity_bill', 'site_photo', 'land_tax_paper', 'name_signature', 'dcr', 'gps_photo', 'inverter_serial_number'])), name='works_document_key_valid')],
            },
        ),
    ]
