# Generated by Django 5.2.17 on 2026-09-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_dashboard', 'Can open the Dashboard'), ('access_work', 'Can open Work'), ('access_activities', 'Can open Activities'), ('access_reports', 'Can open Reports')]},
        ),
    ]
