# Generated by Django 5.2.17 on 2026-09-30 15:04

import django.db.models.deletion
from django.db import migrations, models


def create_roles(apps, schema_editor):
    # Staff start with no modules: an admin chooses them in Settings → Roles & Access.
    Role = apps.get_model('accounts', 'Role')
    Role.objects.create(name='ADMIN', description='Full access to every module and to Settings.')
    Role.objects.create(name='STAFF', description='Access to the modules chosen in Roles & Access.')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff')], max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_role_valid',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission'),
        ),
        # Before `role` becomes a foreign key: the stored "ADMIN"/"STAFF" values then point at these rows unchanged.
        migrations.RunPython(create_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='STAFF', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role'),
        ),
    ]
