# Generated by Django 5.2.17 on 2026-09-30 14:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='System size in kW.', max_digits=5, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['capacity'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='leads_solarplan_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country_code', models.CharField(default='91', max_length=3, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{0,2}$', 'Enter a country code of 1 to 3 digits.')])),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[0-9]{6,14}$', 'Enter the phone number as 6 to 14 digits.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('pin_code', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Enter a 6-digit PIN code.')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INITIAL_CONTACT', 'Initial Contact'), ('HOT', 'Hot'), ('SUPERHOT', 'Superhot'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('WALK_IN', 'Walk-in'), ('PHONE_CALL', 'Phone call'), ('WHATSAPP', 'WhatsApp'), ('REFERRAL', 'Referral'), ('WEBSITE', 'Website'), ('SOCIAL_MEDIA', 'Social media'), ('OTHER', 'Other')], max_length=20)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.solarplan')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='leads_lead_status_idx'), models.Index(fields=['created_at'], name='leads_lead_created_at_idx'), models.Index(fields=['next_follow_up'], name='leads_lead_follow_up_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['NEW', 'INITIAL_CONTACT', 'HOT', 'SUPERHOT', 'WON', 'LOST'])), name='leads_lead_status_valid'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='leads_lead_amount_non_negative')],
            },
        ),
    ]
