# Generated by Django 5.2.17 on 2026-10-01 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_default_solar_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHONE_CALL', 'Phone call'), ('FOLLOW_UP', 'Follow-up'), ('SITE_VISIT', 'Site visit'), ('MEETING', 'Customer meeting'), ('NOTE', 'Note')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['PHONE_CALL', 'FOLLOW_UP', 'SITE_VISIT', 'MEETING', 'NOTE'])), name='activities_type_valid')],
            },
        ),
    ]
