# Generated by Django 5.2.17 on 2026-10-01 10:05

from django.conf import settings
from django.db import migrations, models

from ._operations import AddConstraintIfMissing, AddFieldIfMissing, AddIndexIfMissing


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('leads', '0002_default_solar_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Adds only what the database doesn't have yet: a database migrated on the Work activities branch before it was
    # combined with this one already has some of these (see _operations.py).
    operations = [
        AddFieldIfMissing(
            model_name='activity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        AddFieldIfMissing(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        AddIndexIfMissing(
            model_name='activity',
            index=models.Index(fields=['status'], name='activities_status_idx'),
        ),
        AddIndexIfMissing(
            model_name='activity',
            index=models.Index(fields=['due_date'], name='activities_due_date_idx'),
        ),
        AddIndexIfMissing(
            model_name='activity',
            index=models.Index(fields=['created_at'], name='activities_created_at_idx'),
        ),
        AddConstraintIfMissing(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'COMPLETED'])), name='activities_status_valid'),
        ),
    ]
