# Generated by Django 5.2.17 on 2026-10-01 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('leads', '0002_default_solar_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='activities_status_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['due_date'], name='activities_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_at'], name='activities_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'COMPLETED'])), name='activities_status_valid'),
        ),
    ]
