# Generated by Django 5.2.17 on 2026-10-01 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from ._operations import AddFieldIfMissing


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_status_and_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Adds only what the database doesn't have yet: a database migrated on the Work activities branch before it was
    # combined with this one already has some of these (see _operations.py).
    operations = [
        AddFieldIfMissing(
            model_name='activity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_activities', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfMissing(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
