# Generated by Django 5.2.17 on 2026-10-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_work_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completion_note',
            field=models.TextField(blank=True),
        ),
    ]
