# Generated by Django 5.2.17 on 2026-10-05 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0004_work_activities'),
        ('leads', '0002_default_solar_plans'),
        ('works', '0002_work_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ACTIVITY_ASSIGNED', 'Activity assigned'), ('ACTIVITY_STATUS', 'Activity status updated'), ('LEAD_CREATED', 'Lead created'), ('LEAD_CONVERTED', 'Lead converted to Work'), ('WORK_COMPLETED', 'Work completed'), ('CRM_RESET', 'CRM data reset')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activities.activity')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='leads.lead')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='works.work')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notifications_recipient_idx'), models.Index(fields=['recipient', 'read_at'], name='notifications_unread_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['ACTIVITY_ASSIGNED', 'ACTIVITY_STATUS', 'LEAD_CREATED', 'LEAD_CONVERTED', 'WORK_COMPLETED', 'CRM_RESET'])), name='notifications_kind_valid')],
            },
        ),
    ]
